import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import Header from "./components/Header";
import Footer from "./components/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="preload"
          href="/fonts/Blogger_Sans-Regular.otf"
          as="font"
          type="font/otf"
        />
        <link
          rel="preload"
          href="/fonts/Blogger_Sans-Light.otf"
          as="font"
          type="font/otf"
        />
      </Head>
      <body className="max-w-[1440px] m-auto ">
        <div className="min-h-[100vh] flex flex-col">
          <Header />
          <main className="grow">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
